Laura Würfel-Event mit Sensor
se-ii-mankomania/mankomania-app pull request #50
Opened 2024-04-22 16:37 UTC by laulaobm

Das zuvor provisorisch implementierte Würfelevent verfügt nun über einen Sensor und die Augenzahlen der Würfel werden mithilfe von Drawables ausgegeben. Desweiteren wurde eine Funktion hinugefügt, dass die Activität mithilfe des BackButtons nicht verlassen werden kann, damit der Spielvorgang nicht abgebrochen wird.

Um zu Würfeln wird derzeit ein Button am Board verwendet, dies ändert sich aber, wenn die Spielreihenfolge implementiert ist.

2024-04-23 19:27 UTC, roldka requested changes
Sehr süße Würfel-Bildchen :) 
Insgesamt sehr sauber gelöst, aber bitte noch die kleinen Anpassungen machen :)

2024-04-23 19:27 UTC, roldka commented on app/src/main/java/com/example/mankomania/screens/EventRollDice.java
> +            if ((Math.abs(x) > 10 || Math.abs(y) > 10 || Math.abs(z) > 10)) {
Kannst du hier bitte die 10er als globale threshold-Variable rausziehen? Falls der Wert angepasst werden muss, sollte das dann einfacher gehen :)

2024-04-23 19:27 UTC, roldka commented on app/src/main/res/layout/activity_event_roll_dice.xml
Wäre es evtl sinnvoll, am Rand noch einen kleinen Button einzuführen, der ebenfalls das Würfeln auslöst? So als Backup, falls die Sensoren nicht gehen

2024-04-23 23:21 UTC, laulaobm commented on app/src/main/java/com/example/mankomania/screens/EventRollDice.java
> +            if ((Math.abs(x) > 10 || Math.abs(y) > 10 || Math.abs(z) > 10)) {
super Vorschlag, danke! Ist jetzt implementiert

2024-04-23 23:21 UTC, laulaobm commented on app/src/main/res/layout/activity_event_roll_dice.xml
Auch erledigt, danke!

2024-04-24 08:00 UTC, roldka approved these changes
Super, danke!!

2024-04-24 09:56 UTC, merged