Sonar And Pull-Request Fixes
se-ii-mankomania/mankomania-app pull request #69
Opened 2024-05-23 12:42 UTC by laulaobm

Die Issues auf SonarCloud wie renaming, refactoring allgemein und ein Singleton Pattern wurden angepasst. Außerdem wurden die Vorschläge aus dem Pull-Request von Herrn Lercher miteingebunden.

2024-05-24 13:36 UTC, roldka requested changes
sieht supi aus :) bitte noch den kommentar durchgehen :))

2024-05-24 13:36 UTC, roldka commented on app/src/main/java/com/example/mankomania/api/LobbyAPI.java
du kannst das "riesige" switch-Konstrukt umgehen, indem du diesen Code stattdessen einfügst und den Status IN_GAME zu INGAME änderst:

try {
            status = Status.valueOf(jsonLobby.getString("status").toUpperCase());
        } catch (IllegalArgumentException e) {
            throw new IllegalArgumentException("Ungültiger Status!", e);
        }
        
dann laufen (zumindest bei mir lokal) die tests  auch noch :)
wäre super, wenn du da nochmal schaust, ob das wirklich sinn macht :D

2024-05-24 13:36 UTC, roldka commented on app/src/main/java/com/example/mankomania/api/LobbyAPI.java
ah, ich seh grad, dass du das eh schon ähnlich in der SessionAPI hast :)

2024-05-24 13:39 UTC, laulaobm commented on app/src/main/java/com/example/mankomania/api/LobbyAPI.java
mach ich, habe mich noch nicht getraut, weil ich mich in deinem Code nicht so gut ausgekannt habe

2024-05-26 18:17 UTC, roldka approved these changes
Supiii, danke :)

2024-05-26 19:24 UTC, merged